name: Sync multiple branches
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Pull Latest Main and Test Environment Branches
        run: |
          git fetch origin main
          git fetch origin test-env-1
          git checkout test-env-1
          git pull origin test-env-1
      - name: Merge Latest
        run: |
          git branch