on:
  push:
    branches:
      - "main"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Env. 1
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'test-env-1'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

      - name: Test Env. 2
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'test-env-2'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'