name: Sync multiple branches
on:
  push:
    branches:
      - master
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: test-br-1
        with:
          type: now
          from_branch: master
          target_branch: test-env-1
          github_token: ${{ github.token }}

      - name: Merge staging -> uat
        uses: test-br-1
        with:
          type: now
          from_branch: staging
          target_branch: uat
          github_token: ${{ github.token }}
